services:
  frontend:
    build:
      context: ./galilei-pt
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3001:3001"
