services:
  frontend:
    build:
      context: ./galilei-pt
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - API_KEY=your_api_key
    ports:
      - "8000:8000"
